from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("background-color: rgba(33, 44, 53, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_in_1s = QtWidgets.QPushButton(self.centralwidget)
        self.btn_in_1s.setGeometry(QtCore.QRect(10, 190, 61, 28))
        self.btn_in_1s.setStyleSheet("background-color: rgb(77, 77, 77);")
        self.btn_in_1s.setObjectName("btn_in_1s")
        self.btn_in_5s = QtWidgets.QPushButton(self.centralwidget)
        self.btn_in_5s.setGeometry(QtCore.QRect(90, 190, 61, 28))
        self.btn_in_5s.setStyleSheet("background-color: rgb(77, 77, 77);")
        self.btn_in_5s.setObjectName("btn_in_5s")
        self.btn_in_15s = QtWidgets.QPushButton(self.centralwidget)
        self.btn_in_15s.setGeometry(QtCore.QRect(160, 190, 61, 28))
        self.btn_in_15s.setStyleSheet("background-color: rgb(77, 77, 77);")
        self.btn_in_15s.setObjectName("btn_in_15s")
        self.btn_type_gr_line = QtWidgets.QPushButton(self.centralwidget)
        self.btn_type_gr_line.setGeometry(QtCore.QRect(40, 240, 61, 28))
        self.btn_type_gr_line.setStyleSheet("background-color: rgb(77, 77, 77);")
        self.btn_type_gr_line.setObjectName("btn_type_gr_line")
        self.btn_type_gr_candle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_type_gr_candle.setGeometry(QtCore.QRect(120, 240, 61, 28))
        self.btn_type_gr_candle.setStyleSheet("background-color: rgb(77, 77, 77);")
        self.btn_type_gr_candle.setObjectName("btn_type_gr_candle")
        self.balance = QtWidgets.QLabel(self.centralwidget)
        self.balance.setGeometry(QtCore.QRect(900, 30, 300, 81))
        self.balance.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.balance.setObjectName("balance")
        self.Profile = QtWidgets.QPushButton(self.centralwidget)
        self.Profile.setGeometry(QtCore.QRect(50, 50, 71, 71))
        self.Profile.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.Profile.setObjectName("Profile")
        self.Settings = QtWidgets.QPushButton(self.centralwidget)
        self.Settings.setGeometry(QtCore.QRect(140, 50, 71, 71))
        self.Settings.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.Settings.setObjectName("Settings")
        self.btn_news_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_news_1.setGeometry(QtCore.QRect(900, 170, 300, 71))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_news_1.setFont(font)
        self.btn_news_1.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"gridline-color: rgb(255, 255, 255);")
        self.btn_news_1.setObjectName("btn_news_1")
        self.btn_news_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_news_2.setGeometry(QtCore.QRect(900, 240, 300, 71))
        self.btn_news_2.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.btn_news_2.setObjectName("btn_news_2")
        self.btn_news_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_news_3.setGeometry(QtCore.QRect(900, 310, 300, 71))
        self.btn_news_3.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.btn_news_3.setObjectName("btn_news_3")
        self.btn_news_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_news_4.setGeometry(QtCore.QRect(900, 380, 300, 71))
        self.btn_news_4.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.btn_news_4.setObjectName("btn_news_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(900, 170, 300, 3))
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(900, 0, 3, 800))
        self.line_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(900, 450, 300, 3))
        self.line_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.s_sale = QtWidgets.QPushButton(self.centralwidget)
        self.s_sale.setGeometry(QtCore.QRect(940, 650, 71, 71))
        self.s_sale.setStyleSheet("background-color: rgb(209, 9, 9);")
        self.s_sale.setObjectName("s_sale")
        self.s_buy = QtWidgets.QPushButton(self.centralwidget)
        self.s_buy.setGeometry(QtCore.QRect(1050, 650, 71, 71))
        self.s_buy.setStyleSheet("background-color: rgb(209, 9, 9);\n"
"background-color: rgb(12, 208, 28);")
        self.s_buy.setObjectName("s_buy")
        self.s_plus = QtWidgets.QPushButton(self.centralwidget)
        self.s_plus.setGeometry(QtCore.QRect(1070, 570, 71, 71))
        self.s_plus.setStyleSheet("background-color: rgb(126, 126, 126);")
        self.s_plus.setObjectName("s_plus")
        self.s_minus = QtWidgets.QPushButton(self.centralwidget)
        self.s_minus.setGeometry(QtCore.QRect(950, 570, 71, 71))
        self.s_minus.setStyleSheet("background-color: rgb(126, 126, 126);")
        self.s_minus.setObjectName("s_minus")
        self.s_price = QtWidgets.QLabel(self.centralwidget)
        self.s_price.setGeometry(QtCore.QRect(930, 490, 91, 41))
        self.s_price.setStyleSheet("background-color: rgb(126, 126, 126);")
        self.s_price.setObjectName("s_price")
        self.s_count = QtWidgets.QLabel(self.centralwidget)
        self.s_count.setGeometry(QtCore.QRect(1070, 490, 91, 41))
        self.s_count.setStyleSheet("background-color: rgb(126, 126, 126);")
        self.s_count.setObjectName("s_count")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(230, 0, 3, 800))
        self.line_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(230, 540, 671, 10))
        self.line_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_in_1s.setText(_translate("MainWindow", "1s"))
        self.btn_in_5s.setText(_translate("MainWindow", "5s"))
        self.btn_in_15s.setText(_translate("MainWindow", "15s"))
        self.btn_type_gr_line.setText(_translate("MainWindow", "Line"))
        self.btn_type_gr_candle.setText(_translate("MainWindow", "Candle"))
        self.balance.setText(_translate("MainWindow", "Balance"))
        self.Profile.setText(_translate("MainWindow", "Profile"))
        self.Settings.setText(_translate("MainWindow", "Settings"))
        self.btn_news_1.setText(_translate("MainWindow", "News_1"))
        self.btn_news_2.setText(_translate("MainWindow", "News_2"))
        self.btn_news_3.setText(_translate("MainWindow", "News_3"))
        self.btn_news_4.setText(_translate("MainWindow", "News_4"))
        self.s_sale.setText(_translate("MainWindow", "Продажа"))
        self.s_buy.setText(_translate("MainWindow", "Покупка"))
        self.s_plus.setText(_translate("MainWindow", "+"))
        self.s_minus.setText(_translate("MainWindow", "-"))
        self.s_price.setText(_translate("MainWindow", "Цена"))
        self.s_count.setText(_translate("MainWindow", "штук"))

    def add_functions(self):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    QtWidgets.QWidget.gra
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
